### ISSUE TITLE
Grafana 7

### ISSUE THREAD

**Issue by saliceti** [SpringerPE/cf-grafana-buildpack#5]
Grafana 7 brings a lot of good features: https://grafana.com/docs/grafana/latest/whatsnew/whats-new-in-v7-0/

[We've been using this buildpack](https://github.com/DFE-Digital/get-into-teaching-api/blob/master/terraform/monitoring/modules.tf#L64) with Grafana 7 (currently 7.2.2) successfully for a while now without any issue. But the Readme still says:
> This buildpack only supports Grafana 6.x!

Can it be updated?

**Comment by CelestePhutela** [comment]
@saliceti Apologies for the delay in responding back, we are working on upgrading the Grafana and we will let you know once its done

**Comment by CelestePhutela** [comment]
@saliceti we have upgraded the default Grafana version.

**Comment by saliceti** [comment]
Thanks I'll test it 👍

**Comment by saliceti** [comment]
Tested successfully. Thanks @CelestePhutela I think you can close this issue now 👍
